### ISSUE TITLE
reuse the class variable numStates in PhyloCTMC

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#118]
`PhyloCTMC` already has the class variable `numStates`. Make it `final` and reuse it in `sample()`. It can get from Q matrix length, but since it is stored in the class variable `numStates`, it'd better to be reused.

**Comment by alexeid** [comment]
Remember that all parameters can be reset by setParam!

**Comment by walterxie** [comment]
But the dimension of Q matrix can be changed, otherwise it will be invalid, or it should create another `PhyloCTMC`. So `final` class variable `numStates` makes sure this is correct.

**Comment by walterxie** [comment]
Now it should be handled by SequenceType, also see #136
