### ISSUE TITLE
Duplicated StateNode in RAM

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#125]
run LPhyBEAST given `RSV2.lphy`. The XML has duplicated `DeltaExchangeOperator` for `Dirichlet`. When I check the RAM, there are 2 same StateNode in `states`. One is added by `CompoundVectorToBEAST`, the other is added by `DirichletToBEAST`.

How to avoid `ValueToBEAST` and `GeneratorToBEAST` add the same StateNode?

**Comment by alexeid** [comment]
ValueToBEAST should do this work. GeneratorToBEAST should only create StateNodes when they don’t already exist in the correct form from the ValueToBEAST.

**Comment by walterxie** [comment]
After I dug this deeper, I found the bug was actually insider `addToContext(...)`where the duplicate check was missing after unwrapping `BEASTVector`.
In addition, I located two places to fill in the BEASTContext, which seems very easy to misuse the method `putBEASTObject(...)`, hence the same context could be added twice. I add the comments to all related places to remind this problem.
