### ISSUE TITLE
Add legend on the bottom of alignment viewer

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#137]
Add legend on the bottom of alignment viewer to show which colour is mapping to which state.

**Comment by walterxie** [comment]
<img width="734" alt="Screen Shot 2022-09-23 at 4 19 54 PM" src="https://user-images.githubusercontent.com/5743014/191891438-93803bdb-4774-4675-843f-3dcdf49a17dc.png">

**Comment by walterxie** [comment]
Amino Acids

<img width="721" alt="Screen Shot 2022-09-23 at 4 20 19 PM" src="https://user-images.githubusercontent.com/5743014/191891494-2f40f71b-e7d3-4ad6-9649-55d0dcefb6b2.png">

**Comment by walterxie** [comment]
Binary:

<img width="722" alt="Screen Shot 2022-09-23 at 4 21 41 PM" src="https://user-images.githubusercontent.com/5743014/191891598-abcd49d7-ec76-48e9-85a9-8ff8b48b5396.png">

**Comment by alexeid** [comment]
Would white letters be more visible?

**Comment by walterxie** [comment]
No good for yellow background

<img width="174" alt="Screen Shot 2022-09-27 at 10 15 14 AM" src="https://user-images.githubusercontent.com/5743014/192381947-efa23d9d-8e3a-429a-b6eb-3ed907266fc7.png">

**Comment by walterxie** [comment]
You can press and hold the button to see the letter, the background will change to light grey. I cannot make a screenshot for this function.

**Comment by alexeid** [comment]
you could do the letters with a different paint mode. Wrap your drawText method in a pair of g.setXORColor(Color) and g.setPaintMode(). Then you will always get good contrast no matter what the background.

**Comment by walterxie** [comment]
I attempted to use paint mode, but it ended with more complex development, because these are `SquareButton`. After some research, I find comparing `backgroundColor.getRGB()` from each `SquareButton` to an empirical threshold makes me easy to adjust the text colour, and I do not have to rewrite all drawing and spacing. Here is the example, and it works fine:

<img width="683" alt="Screen Shot 2022-09-27 at 2 18 48 PM" src="https://user-images.githubusercontent.com/5743014/192409153-117ba510-696d-41f3-976f-ea28b89de0bd.png">
