### ISSUE TITLE
the Greek characters rendered incorrectly in Windows

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#145]
the Greek characters rendered incorrectly in Windows

![image](https://user-images.githubusercontent.com/5743014/122126991-a428aa00-ce86-11eb-8e6e-97aa127afd28.png)

**Comment by alexeid** [comment]
I Found this googling. Good be the problem. I don't think it was all Windows machines, just one:

The Java virtual machine handles Unicode support through a system of specialized language objects called "locales." These combine Unicode language support with standard settings for the currency systems, numbers and other characters that change from region to region. If you don't specify a different locale or font group, the JVM will load a locale based on the language the client's operating system is currently using. If the locale's default language set does not support the Unicode set your program is trying to use, the program will not be able to display the Unicode characters.

**Comment by walterxie** [comment]
What about :

```
public class LinguaPhyloStudio {
    ...
    static {
        Locale.setDefault(Locale.ENGLISH);

        System.setProperty("apple.eawt.quitStrategy", "CLOSE_ALL_WINDOWS");
...
```

**Comment by alexeid** [comment]
I think we have to first establish if this is the problem. We need a Windows machine that is set to a European locale or something. Or maybe we could set the Locale to something else and see if it causes problems?

**Comment by walterxie** [comment]
I tried Locale.CHINESE, Locale.ITALY, Locale.KOREA, they all were fine. I think it may be caused by the OS using a default font that did not support unicode.

https://stackoverflow.com/questions/46703359/swing-jlabel-display-unicode-u21b5-as-text-not-working

**Comment by walterxie** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/5743014/171776255-c8d97ebd-9bfe-4053-b7fa-70fd47a414d5.png)

**Comment by walterxie** [comment]
The installbuilder somehow changed the setting of encoding, so try to set encoding to UTF-8 to JVM.
