### ISSUE TITLE
Add option to generate output files without special unicode characters

### ISSUE THREAD

**Issue by kche309** [LinguaPhylo/linguaPhylo#151]
Currently using special math characters in the lphy script produces output variable logs with special characters. 
It would be helpful to have an option to output these variables as latin characters (e.g. π_0 as pi_0, κ as kappa, Θ as theta).

Example hkyCoalescent.lphy script 
https://github.com/LinguaPhylo/linguaPhylo/blob/fcbda992ee31317375403d2033a99ec8464c9c1e/examples/hkyCoalescent.lphy#L1-L5

Example output variables log
```
sample	π_0	π_1	π_2	π_3	κ	Θ
0	0.4307621416142515	0.14230930308589138	0.2727011930644103	0.1542273622354468	1.5614144727584072	32.193224941143
```

Example output variables log to latin characters
```
sample	pi_0	pi_1	pi_2	pi_3	kappa	theta
0	0.4307621416142515	0.14230930308589138	0.2727011930644103	0.1542273622354468	1.5614144727584072	32.193224941143
```

**Comment by walterxie** [comment]
this is solved #156
