### ISSUE TITLE
Distributions, tree priors, and samplers should share a single random generator

### ISSUE THREAD

**Issue by kche309** [LinguaPhylo/linguaPhylo#152]
To ensure output is reproducible, all distribution and samplers should share a single random number generator, such as `lphy.core.distributions.Utils.getRandom()`

Currently some distributions are creating a new random number generator when sampling.

Additionally, we should allow the seed of the random number generator to be set as a program argument e.g.  `-seed 123`

**Comment by walterxie** [comment]
It looks very messy how using RandomGenerator. I am going to refactoring section by section. But using setSeed in lphy script is a fundamental change, it may create another issue for it.

Proposed changes are :
1. every LPhy classes use one static random in Utils. 
2. all trees invoke Utils.getRandom in their super abstract class TaxaConditionedTreeGenerator , which is existing code but some trees are not followed.
3. For all GenerativeDistribution , no idea how to create an abstract class, so I have to add random to Apache dist one by one.
4. I will leave Func for now, they seem not to require any random as far as I know.

**Comment by walterxie** [comment]
I think `constructDistribution();` should move to interface `GenerativeDistribution` as a general guide.

**Comment by walterxie** [comment]
`RandomBooleanArray` requires `java.util.Random`, so cache 2 randoms in `Utils` at the moment. Seeking better solution.

**Comment by walterxie** [comment]
#207

**Comment by walterxie** [comment]
The template for discrete distributions (Integer) and continuous distributions (Double):

https://github.com/LinguaPhylo/linguaPhylo/blob/c540c030eb9c59bf465cdc9f445c691e0c5038fc/lphy/src/main/java/lphy/core/distributions/PriorDistributionGenerator.java

The implementation requires `super()` and `constructDistribution(RandomGenerator)`, and setParam is no longer required, an example is :

https://github.com/LinguaPhylo/linguaPhylo/blob/c540c030eb9c59bf465cdc9f445c691e0c5038fc/lphy/src/main/java/lphy/core/distributions/Beta.java

**Comment by walterxie** [comment]
For any tree priors inherited from `TaxaConditionedTreeGenerator` should use the `random` assigned from its parent constructor.
