### ISSUE TITLE
Not use the special characters for logging in the simulation

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#156]
For example, load `RSV2.lphy` in the tutorial, and click the `Sample` button to make a simulation, then the true tree is logged into a file named as `RSV2_true_ψ.trees`.

`ψ` could be a trouble for OS using some languages not English.

**Comment by kche309** [comment]
Hi Walter, there's also a similar issue for variable names within the log files https://github.com/LinguaPhylo/linguaPhylo/issues/151

**Comment by walterxie** [comment]
It is now fixed:
sample	pi_0_0	pi_0_1	pi_0_2	pi_0_3
