### ISSUE TITLE
Always getting parser from GraphicalModelComponent

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#174]
@alexeid I am trying to simplify studio GUI logic. I suggest : 

1. The 1st improvement is that we should make an agreement of using `GraphicalModelComponent` to keep the parser and its variables and functions. So we get parser from GraphicalModelComponent when it is required.
2. Then `GraphicalModelPanel` is the container of `GraphicalModelComponent ` 
3. Eventually move all business logics out from main class `LinguaPhyloStudio`. The benefit is that we do not have to create LinguaPhyloStudio instance to get parser or GraphicalModelComponent insider `lphystudio` package.

Not sure `GraphicalModelInterpreter extends JPanel` should be simplified.

**Comment by walterxie** [comment]
Not sure why we need cross interaction, but it still works after commenting out 2nd line:
 ```java
       component.addGraphicalModelListener(listener);
//        parser.addGraphicalModelChangeListener(component);
```

**Comment by alexeid** [comment]
Maybe you shouldn’t comment out things if you don’t know what they are doing? 😊

From: Walter ***@***.***>
Date: Friday, 29 April 2022 at 1:30 PM
To: LinguaPhylo/linguaPhylo ***@***.***>
Cc: Alexei Drummond ***@***.***>, Mention ***@***.***>
Subject: Re: [LinguaPhylo/linguaPhylo] Always getting parser from GraphicalModelComponent (Issue #174)

Not sure why we need cross interaction, but it still works after commenting out 2nd line:

      component.addGraphicalModelListener(listener);

//        parser.addGraphicalModelChangeListener(component);

**Comment by walterxie** [comment]
You are right. They are two different listeners. I was confused with Model and ModelChange. Uncomment the line.
