### ISSUE TITLE
probit function should be numerical implementation of the inverse error function 

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#237]
https://en.wikipedia.org/wiki/Probit#Computation suggests `probit(p)=sqrt(2)*inverse_erf(2p-1)`, but the lphy implementation uses `erf`:

```java
Math.sqrt(2) * org.apache.commons.math3.special.Erf.erf(2 * a.doubleValue() - 1);
``` 

I think it should be `Erf.erfInv(...)` in term of Apache math doc and wiki.

**Comment by alexeid** [comment]
Maybe. We should sample from the distribution and check it gives the right expectation in a unit test.

**Comment by walterxie** [comment]
I confirm `probit(p)=sqrt(2)*inverse_erf(2p-1)`. The unit test is added.
