### ISSUE TITLE
Allow data clamping the alignment simulated by 2nd lphy script

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#260]
```
data {
  D = simulate(lphy="examples/coalescent/jcSimData.lphy", alignmentId=["F"]);
  taxa = D.taxa();
  L = D.nchar();
}
model {
  Θ ~ LogNormal(meanlog=3.0, sdlog=1.0);
  ψ ~ Coalescent(theta=Θ, taxa=taxa);
  D ~ PhyloCTMC(tree=ψ, L=L, Q=jukesCantor());
}
```

**Comment by alexeid** [comment]
Awesome!

**Comment by walterxie** [comment]
The D is not clamped

<img width="1712" alt="Screen Shot 2022-12-13 at 9 41 52 AM" src="https://user-images.githubusercontent.com/5743014/207150184-0c158b44-a506-4a92-8f9a-854737461283.png">

<img width="1712" alt="Screen Shot 2022-12-13 at 9 42 29 AM" src="https://user-images.githubusercontent.com/5743014/207150313-16f7a0a8-f651-4d96-a96c-48ef7a2b07e1.png">

**Comment by walterxie** [comment]
I suspect the problem may be caused by different types of D.

**Comment by walterxie** [comment]
<img width="1712" alt="Screenshot 2022-12-16 at 11 10 10 AM" src="https://user-images.githubusercontent.com/5743014/208010880-f4a5cbd3-f66a-4ebe-be15-3eaf320deaac.png">

<img width="1712" alt="Screenshot 2022-12-16 at 3 50 50 PM" src="https://user-images.githubusercontent.com/5743014/208011001-8cef5823-5aa3-4c2d-a9f9-41dd13016fb6.png">
