### ISSUE TITLE
Create GitHub page for the LPhy Language Reference

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#310]
Create GitHub page (webpage) for the LPhy Language Reference, instead of showing the rendered page from GitHub.

**Comment by walterxie** [comment]
I am not the admin of this repo. @alexeid can you please create the empty site following the instruction  https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site? So we will fill in the content.

**Comment by walterxie** [comment]
#331

**Comment by kche309** [comment]
Docs are currently copied to the `docs` subdirectory of the webpage repo: https://github.com/LinguaPhylo/linguaPhylo.github.io/tree/master/docs

Main page of the manual `index.md` is referenced from  https://github.com/LinguaPhylo/linguaPhylo.github.io/blob/master/docs.md

**Comment by walterxie** [comment]
It is done https://linguaphylo.github.io/linguaPhylo/. But the link to homepage on the top left corner needs to correct to  https://linguaphylo.github.io
