### ISSUE TITLE
Dirichlet example script throws exception

### ISSUE THREAD

**Issue by kche309** [LinguaPhylo/linguaPhylo#313]
The script in examples/dirichlet.lphy can generate variable logs, but throws a `java.lang.UnsupportedOperationException`.

The error message may be thrown by the `sum()` function.

**Comment by walterxie** [comment]
I cannot reproduce
<img width="1367" alt="Screenshot 2023-04-05 at 9 46 16 AM" src="https://user-images.githubusercontent.com/5743014/229929869-5e4dbe50-461a-4d11-9b06-d267f76dc966.png">

**Comment by kche309** [comment]
I previously produced this error running LPhyStudio using IntelliJ, but cannot reproduce the error anymore. 
I'm closing this Git Issue because it looks like it has been fixed.
