### ISSUE TITLE
RSV2 narrative metadataalignment

### ISSUE THREAD

**Issue by kche309** [LinguaPhylo/linguaPhylo#316]
Text for the RSV2 example, has the word "metadataalignment D". 
The word "metadataalignment D" should be changed to "metadata alignment D"?
![RSV2](https://user-images.githubusercontent.com/8745224/229648940-504bc333-3726-419c-b175-2ec9932ed2ec.png)

**Comment by walterxie** [comment]
Add an interface to get a pretty narrative name for those classes whose class name is not human readable.

**Comment by alexeid** [comment]
Shouldn’t it just be “alignment”?On 26/04/2023, at 2:55 PM, Walter ***@***.***> wrote:﻿
Closed #316 as completed.

**Comment by walterxie** [comment]
I thought to distinguish the alignment having meta-data with the one having no meta-data.

**Comment by alexeid** [comment]
Sure, that is fine.On 27/04/2023, at 9:27 AM, Walter ***@***.***> wrote:﻿
I thought to distinguish the alignment having meta-data with the one having no meta-data.
