### ISSUE TITLE
Command line slphy scripts produce ClassNotFoundException

### ISSUE THREAD

**Issue by kche309** [LinguaPhylo/linguaPhylo#327]
Running slphy from command line after installing LPhyStudio on mac produces `java.lang.ClassNotFoundError` because variable `LPHY` is not set properly. 

Should modify installer or script to use correct variable for path. 

```
/Applications/BEAST\ 2.7.3/lphy/bin/slphy
Error: Could not find or load main class 2.7.3.lphy.lib
Caused by: java.lang.ClassNotFoundException: 2.7.3.lphy.lib
```

**Comment by walterxie** [comment]
The spaces in the folder name will make a trouble.
