### ISSUE TITLE
Dirichlet function cannot take replicates

### ISSUE THREAD

**Issue by bredelings** [LinguaPhylo/linguaPhylo#337]
Hi,

Trying out lphy studio 1.4, if I change
```
rates ~ Dirichlet(conc=[100.0,100.0,100.0,1000.0]);
```

to

```
rates ~ Dirichlet(conc=[100.0,100.0,100.0,1000.0], replicates=2);
```

then the status bar says "Read LPhy script from null".  It would be nice if a more descriptive error messages was given.

**Comment by kche309** [comment]
@bredelings Thanks for reporting this bug. I assume you are modifying the dirichlet example script? 
https://github.com/LinguaPhylo/linguaPhylo/blob/master/examples/dirichlet.lphy 

We are currently fixing the `sum()` function used by the `dirichlet.lphy` example to handle replicates. 

Note that both `rates` and `weights` would need to have the same dimensions. 
```
weights = rep([100.0,100.0,100.0,1000.0], 2);
rates ~ Dirichlet(conc=[100.0,100.0,100.0,1000.0], replicates=2);
```

**Comment by bredelings** [comment]
My apologies.. you are right.  If I remove the later lines, it seems like the Dirichlet function can indeed take replicates.

**Comment by kche309** [comment]
We have opened two git issues to allow correct handling of vectorization for this example when adding replicates: 
* https://github.com/LinguaPhylo/linguaPhylo/issues/341 to allow`sum()` function to handle a matrix
* https://github.com/LinguaPhylo/linguaPhylo/issues/339 for multiplication of two matrices to default to element-wise multiplication

Fixes will be updated on the new git issues above.
