### ISSUE TITLE
No viewer for 2d Integer array

### ISSUE THREAD

**Issue by bredelings** [LinguaPhylo/linguaPhylo#338]
Hi,

If I write
```
z = [[1,2,3], [4,5,6]]
```

then the file loads, but says 
```
SEVERE: Found no viewer for z=[[1,2,3],[4,5,6]].
```

-BenRI

**Comment by walterxie** [comment]
Add viewer for 2d Integer array, and also fix the bug in the Constants panel. Update the example script https://github.com/LinguaPhylo/linguaPhylo/blob/master/examples/indexing.lphy

**Comment by walterxie** [comment]
<img width="368" alt="Screenshot 2023-05-05 at 2 55 58 PM" src="https://user-images.githubusercontent.com/5743014/236369039-cd04192e-1c80-4694-85c1-002b038cce89.png">


<img width="221" alt="Screenshot 2023-05-05 at 2 56 04 PM" src="https://user-images.githubusercontent.com/5743014/236369049-d8470d5e-0846-452e-9e39-29e67f4c0bee.png">
