### ISSUE TITLE
Element-wise multiplication operator for matrices

### ISSUE THREAD

**Issue by kche309** [LinguaPhylo/linguaPhylo#339]
Multiplication operator should default to element-wise multiplication for matrices. This should be documented in the language features and docs. 

Example:
```
numReps = 2;
weights = rep([100.0,100.0,100.0,1000.0], numReps);
rates ~ Dirichlet(conc=[100.0,100.0,100.0,1000.0], replicates=numReps);
product = rates * weights;
```

**Comment by walterxie** [comment]
In the core interface ElementWise2Args<R,S>, there is an issue where every for loop related to the length of the second dimension of the 2D array was mistakenly referring to the length of the first dimension. This can lead to a NULL exception being thrown if the lengths of the two dimensions are not equal, as is the case with a 2x3 matrix.
