### ISSUE TITLE
Document meaning of (i) replicates and (ii) applying a function to a list.

### ISSUE THREAD

**Issue by bredelings** [LinguaPhylo/linguaPhylo#343]
1. Right now it seems that 
```
x ~ Dirichlet(conc=[1,1,1,1])
n = length(x)
```
leads to n=4.

But,
```
x ~ Dirichlet(conc=[1,1,1,1], replicates=1)
n = length(x)
```
leads to n=1.

So, apparently, specifying replicates always changes the result into a vector, even if replicates=1.  I presume that if any vectors are supplied where a vector is not expected, the result is changed from type  `a` -> `vector<a>`. It would be good to document what's going on here.

2. Secondly, for many functions f, applying f to a vector of values [x1,x2,...] leads to applying the function element-wise, leading to [f(x1), f(x2), ...].  That is, for some functions, `f(x)` is interpreted as `map(f,x)`.

However, for functions that operate on lists, such as `length( )`, this is not the case.  Thus `length(x)` is _not_ interpreted as `map(length,x)`.  So, for lists of lists, it isn't really clear what to expect.  Thus, the difference in `n = length(x)` in the two examples above.  It might be helpful to document this.

This seems like one of the side-effects of handling for-loops implicitly by operating on lists/vectors.

**Comment by alexeid** [comment]
Thanks for the feedback Ben! It is very valuable. From your perspective what is the most appropriate behaviour for replicates=1? Do you think it should behave the same as no replicates?

I guess what you are driving at is: if I have a model that is not vectorised, can I vectorise it with the minimum possible intervention, like just adding a replicates=X in one place, and have everything else work. When does this work, and when does it fail?

We welcome any concrete advice on what behaviour you think is most appropriate, especially if you have a good use case.

From: Benjamin Redelings ***@***.***>
Date: Friday, 5 May 2023 at 3:57 PM
To: LinguaPhylo/linguaPhylo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LinguaPhylo/linguaPhylo] Document meaning of (i) replicates and (ii) applying a function to a list. (Issue #343)

  1.  Right now it seems that

x ~ Dirichlet(conc=[1,1,1,1])

n = length(x)

leads to n=4.

But,

x ~ Dirichlet(conc=[1,1,1,1], replicates=1)

n = length(x)

leads to n=1.

So, apparently, specifying replicates always changes the result into a vector, even if replicates=1. I presume that if any vectors are supplied where a vector is not expected, the result is changed from a -> vector<a>. It would be good to document what's going on here.

  1.  Secondly, for many functions f, applying f to a vector of values [x1,x2,...] leads to applying the function element-wise, leading to [f(x1), f(x2), ...]. That is, for some functions, f(x) is interpreted as map(f,x).

However, for functions that operate on lists, such as length( ), this is not the case. Thus length(x) is not interpreted as map(length,x). So, for lists of lists, it isn't really clear what to expect. Thus, the difference in n = length(x) in the two examples above. It might be helpful to document this.

**Comment by bredelings** [comment]
Hi Alexei,

> Thanks for the feedback Ben! It is very valuable. From your perspective what is the most appropriate behaviour for replicates=1? Do you think it should behave the same as no replicates?

Glad you like the feedback!   I _think_ treating `replicates=1` differently than no `replicates` makes more sense.  I (personally) value consistency.  But I don't have a strong feeling.

For another possible approach, I feel like there are languages (matlab?) where 1 really means [1].  Perhaps such languages would treat `replicates=1` the same as no replicates.  That seems like an alternative approach -- but it seems like either approach is fine as long as there's an underlying rule being follows.  In the matlab approach, one question might be "why does 1 not mean [[1]] and [[[1]]]?"  Probably there's an answer, but I'm not much of a matlab user.


> I guess what you are driving at is: if I have a model that is not vectorised, can I vectorise it with the minimum possible intervention, like just adding a replicates=X in one place, and have everything else work. When does this work, and when does it fail?

Right.  I'm curious about how far you can get without with vectorization instead of either for-loops or an explicit `map` operator.  It seems like the idea is to treat indices implicitly instead of explicitly doing stuff with `x[i]`.  

Treating `f(x)` like `map f x` except when `f` takes a list argument is not perfect, but as long as the user can predict/understand what is going on, that seems fine.  So, documenting it somehow seems important.

In most cases the vectorization approach seems more readable and much simpler.  But I guess my main question is - when it fails, what is the alternative?  And secondarily, I suppose, in which kind of cases does it fail.

**Comment by bredelings** [comment]
I kind of expect the use cases to come up by actually trying to use LPhy and then being surprised.  I'll let you know if I come across one.

**Comment by walterxie** [comment]
Alexei and I think we should not apply IID if replicates = 1. I created a simple example file `vect.lphy` to show this behaviour :

<img width="1132" alt="Screenshot 2023-05-12 at 3 39 31 PM" src="https://github.com/LinguaPhylo/linguaPhylo/assets/5743014/1b306c02-01ac-44df-823b-cd6bf9c1699b">

**Comment by walterxie** [comment]
Here is the configuration if you want to run the studio from IDE such as IntelliJ:

<img width="1152" alt="Screenshot 2023-05-12 at 3 43 47 PM" src="https://github.com/LinguaPhylo/linguaPhylo/assets/5743014/56431873-28b6-4a41-9146-424096fb6fa7">

**Comment by walterxie** [comment]
@bredelings 

In your case, the "replicates=1" was creating a vector of vector, so length(x) resulted to 1. We have change this behaviour to maintain the original dimension when and only when "replicates=1". So the current result (please try examples/vect.lphy) will be 4 using the latest version of master branch.

`length` is the special case in term of vectorisation. If length(2d matrix), then it will return the 1st dim of 2d. If length(matrix[0]), then it will return the 2nd dim. Here matrix[0] is also the vector.

**Comment by walterxie** [comment]
I did not realise that returning the generator instance when `replicates=1`  could be so problematic. In the graph, if replicates is removed (creating instance instead of IID), then the `k ~ Poisson(lambda=1.0, min=1); `will be lost. Unless it returns IID, but then length([[1,2]]) would be 1 again.

Testing script:
```
// replicates = 1, 2, 3, ...
k ~ Poisson(lambda=1.0, min=1);
pi ~ Dirichlet(conc=[1, 1, 1, 1], replicates=k);
L = length(pi);
```

Perhaps, we should `let length([[1,2]])` to 1, then document this to users.

**Comment by bredelings** [comment]
> Perhaps, we should let length([[1,2]]) to 1, then document this to users.

Yeah, I think so.

The underlying problem is that the two cases
1. `length([[1,2]])=1` -- function application
2. `length([[1,2]])=2` -- map
Use the same syntax for two different operations.  In some cases you can determine which one should be used from context -- but not in all cases.  It does seem that 1. (function application) should be preferred.

Because context cannot always tell you whether to do 1. or 2, it seems that you cannot completely solve this problem without adding a second syntax form.

**Comment by bredelings** [comment]
After thinking about it, I think I prefer that replicates=n always means iid.  Or, you could introduce an explicit iid, and forbid replicates from being random and require replictes >= 2.

**Comment by walterxie** [comment]
#353 #350

**Comment by walterxie** [comment]
I think we have solved your problems and answered your questions. The issue and discussions related to empty array is recorded  in https://github.com/LinguaPhylo/linguaPhylo/issues/353. 

Thank you very much for your efforts. I am going to close this issue and #353 in this week. If you have any further questions or would like to provide feedback or suggestions, please don't hesitate to reopen these issues or create a new issue.
