### ISSUE TITLE
add product(array[]) function

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#360]
add `product(array[])` function

**Comment by walterxie** [comment]
```
n ~ Poisson(lambda)
scaleFactors ~ LogNormal(mu,sigma,replicates=n)
finalRate = initialRate * product(scaleFactors)
```

**Comment by walterxie** [comment]
See also #350

**Comment by walterxie** [comment]
<img width="776" alt="Screenshot 2023-05-23 at 1 50 42 PM" src="https://github.com/LinguaPhylo/linguaPhylo/assets/5743014/58e05790-5190-4693-80ff-1afd667d1fe4">

**Comment by alexeid** [comment]
What are the black "0" for in the output of length and "length(scaleFactors)>1"? Shouldn't we suppress "unnamed" argument names and just have the value instead?
