### ISSUE TITLE
Remove SequenceType SPI

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#396]
It is not essential for SequenceType to be extendable. The current code is to make the NexusParser keyword about datatype is extendable. See `sequenceType = SequenceTypeLoader.getDataType(token3);`  in line 387.

Find an alternative solution to address this issue without relying on the extension of SequenceType.

**Comment by alexeid** [comment]
I think SPI is a perfectly reasonable approach. It is just nothing to do with the core if a 3rd party package wants to extend the nexus function in the standard library.

**Comment by walterxie** [comment]
see #294
