### ISSUE TITLE
 Need for String types

### ISSUE THREAD

**Issue by rbouckaert** [LinguaPhylo/linguaPhylo#40]
The Newick class takes a tree in Newick format as input, which is of type String. Having a `StringValue` class would fit quite nice with the other `james.graphicalModel.types.Value` classes. Not sure whether we need `StringValueArray` and/or `StringValue2DArray` as well.

**Comment by alexeid** [comment]
Implemented in lphy.graphicalModel.types.StringValue, lphy.graphicalModel.types.StringArrayValue and lphy.graphicalModel.types.StringArray2DValue
