### ISSUE TITLE
Unit test getOldestNode()

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#460]
`TimeTreeNode observe = tree.getOldestNode(randomAge);` can return null randomly, which causes the test failed.

**Comment by walterxie** [comment]
```java
          if (node.getAge() <= maxAge) {
                double nodeAge = node.getAge();
                if (nodeAge > temp) { // if every nodeAge after the 1st "if" are 0s, then this will be always false 
                    temp = nodeAge;
                    tempNode = node;
                }
            }
```

when `maxAge = 0`, if every `nodeAge` after the 1st "if" are 0s, then this will be always false. Therefore it will return null.

**Comment by alexeid** [comment]
But isn't null a valid return value? Because there might be no node older than some given age.

**Comment by walterxie** [comment]
We cannot handle `null ` in lphy. Say lphy code : `node = tree.getOldestNode(t);` then if node is null, the whole lphy script is broken. I suggest to throw Exception, because it will have a nice error message at least.

**Comment by walterxie** [comment]
getOldestNode is renamed to getOldestInternalNode for clarification
