### ISSUE TITLE
IllegalArgumentException in sampler

### ISSUE THREAD

**Issue by yxu927** [LinguaPhylo/linguaPhylo#485]
When I try running jcCoalescent.lphy, when I sample once it seems ok, but when I try clicking sample button, it gives me exception like this:

`Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Try to remove the value E = nucleotide alignment 7 by 200, which was not existing in parser model dictionary previously !`

**Comment by walterxie** [comment]
1. fix sampler to correctly handle the (deterministic func) sink correctly.
2. run tests on re-sampling for all examples;
3. improve doc.
