### ISSUE TITLE
let PhyloCTMC use branch rates from tree if not given

### ISSUE THREAD

**Issue by EvaLiyt** [LinguaPhylo/linguaPhylo#491]
Make branchRates an optional parameter. If branchRates are given, then consider it a relaxed clock. If branchRates are not given and the tree has its own branch rates, then consider it a local clock. Otherwise, consider it a strict clock with a rate of 1.0.

**Comment by alexeid** [comment]
In what sense do you "consider it a local clock"? Do the branch rates in the tree just get used to generate the alignment, regardless of how they were generated?

**Comment by kche309** [comment]
The branch rates on the tree metadata are used to generate the alignment when the branchRates input is not given explicitly.
@alexeid I think what she means is that in the current code only the "local clock" and "subsampleTree" generate branch rate metadata on the tree.

**Comment by kche309** [comment]
There is no assumption that the branch rates metadata of a tree must be from a local clock.
