### ISSUE TITLE
make TaxaCharacterMatrix loggable

### ISSUE THREAD

**Issue by clem-xry** [LinguaPhylo/linguaPhylo#517]
change the logger to log TaxaCharacterMatrix instead of Alignments
add TaxaCharacterMatrix formatter

**Comment by walterxie** [comment]
This should be done properly by implementing `TextFileFormatted`.

See https://github.com/alexeid/toroidalDiffusion/issues/4

https://github.com/alexeid/toroidalDiffusion/blob/1b3c063fbc2fb974d75ae9394b685bf550ecb360/torodiff-lphy/src/main/java/toroidaldiffusion/DihedralAngleAlignment.java#L14
