### ISSUE TITLE
Data clamping bug

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#532]
`public static boolean isDataClamping(Var varInModel, LPhyParserDictionary parser)` used in parser should not use `getModelDictionary().containsKey(id) ` to compare var in model block, because this line has been completely parsed into lphy obj.

**Comment by alexeid** [comment]
I don't understand this error? It seems that the error is in how the model dictionary is populated in current code... This code should work as intended so I would say that some other code has broken the contract.
