### ISSUE TITLE
Load data from Nexus file

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#55]
Load data from Nexus file, such as alignment, dates, traits, ...

**Comment by walterxie** [comment]
@alexeid The 1st part of using fixed 3 taxa internal alignment working version is ready. The command line is `LPhyBEAST -n anything.nex simpleSerialCoalescent.lphy`, but you have to change `ages=[0.0,1.0,2.0]` in `simpleSerialCoalescent.lphy`. Same as `simpleCoalescent.lphy` (n=3). 
The alignment is fixed inside the code `DataExchanger`, since the parser part was not tested yet. 
The taxa mapping method is very simple at the moment, just by ordering. I will improve this next week.

**Comment by walterxie** [comment]
If you use `LPhyBEAST ???Coalescent.lphy`, it will produce XML using simulated alignment.

**Comment by walterxie** [comment]
Regarding the taxa mapping to time tree and traits, I only can think of using an additional mapping file, which must require precise relations in the file. Especially the (number of) taxa or dates in the LPhy langue must be consistent to the mapping file. If you have any better solutions, please let me know.

**Comment by walterxie** [comment]
@alexeid the 1st working example is ready `LPhyBEAST -n Dengue4.nex cmdSimpleCoalescent.lphy`. I used `%ntaxa%` to declare the replacement, which can be discussed. I was struggling to use any reserved char in java reg, so I had to give up to use % to be able to push this forwards.

**Comment by alexeid** [comment]
Nice start Walter! One little problem: I think those Dengue4 sequences should be treated as serially sampled? But beside that I have added and argi function, so that defaults can be added when the argument is missing and also to allow the LPHY script to still run within LPhy Studio. Can you pull and check it out? All you need to do is call ArgI.putArgument(name, value) and then run the script :)

**Comment by alexeid** [comment]
I like your solution for how tidy it is, but then it becomes a template, rather than a script. We could possibly improve LinguaPhylo Studio to automatically pick up these preprocessing tags and populate them from a table or something. We should think about which solution is the best.

**Comment by walterxie** [comment]
Dengue4 was planned to be the example of serially sampled model, which is today's TODO :-)

**Comment by walterxie** [comment]
I think the 6th design looks good, but I am a bit of struggling to implement it at the moment. But I made the 3rd solution working with integer args only, so we would have an example to demonstrate. Though there is nothing different in the output XML, but the implementation is fitted into the 3rd design. 
Try `LPhyBEAST -n Dengue4.nex -m n=ntax|L=nchar cmdSimpleCoalescent.lphy`.

**Comment by alexeid** [comment]
I don't understand why you would repeat this information in the command line:

n=ntax|L=nchar

the n="ntaxa" and L="nchar" mapping is already contained in the two argi() function calls. You don't need to repeat this information in the command line. That is unnecessary redundancy. What if the argi() name parameter doesn't match what you put in the command line?

**Comment by walterxie** [comment]
This is not necessary to repeat. But I was considering the multiple alignments, then, we have to distinguish multiple `nchar` (maybe not `ntaxa`).  So I prefer your dictionary solution, where those `nchar` kind of properties are explicitly linked to the alignment.

**Comment by alexeid** [comment]
Not sure how my dictionary solution helps in the way that you think. You should construct an example.

**Comment by walterxie** [comment]
Please see slide 13.

**Comment by alexeid** [comment]
I think eighth attempt wins. See last slide :)

**Comment by walterxie** [comment]
It shouldn't have to rewrite the taxa in the coalescent tree when you set `clamp=true`:
Using `ψ ~ Coalescent(theta=Θ, taxa=d);`

**Comment by walterxie** [comment]
```Nexus
BEGIN CALIBRATION;
	OPTIONS SCALE = years;
		
	TIPCALIBRATION
		94 = 1994:D4ElSal94,
		86 = 1986:D4PRico86,

```

**Comment by walterxie** [comment]
Also support e.g.
```
1994-07-02:D4ElSal94, 
1986-10-30:D4PRico86
```

**Comment by walterxie** [comment]
Implement  AgeMode = {forward, backward, age} in CALIBRATION OPTIONS.

**Comment by walterxie** [comment]
revert AgeMode

**Comment by walterxie** [comment]
Add guess date:
```
D = nexus(file="examples/RSV2.nex");
taxa = guessAges(taxa=D, regx="s(\d+)$", ageType="forward");
```

**Comment by walterxie** [comment]
```
codon1 = nexus(file="examples/RSV2.nex", charset="1-629\3");
codon2 = nexus(file="examples/RSV2.nex", charset="2-629\3");
codon3 = nexus(file="examples/RSV2.nex", charset="3-629\3");
```
the original multiple partitions are loaded by:
```
coding = nexus(file="examples/primate.nex", part="coding");
noncoding = nexus(file="examples/primate.nex", part="noncoding");
```

**Comment by walterxie** [comment]
codon = nexus(file="examples/RSV2.nex", charset=["1-629\3", "2-629\3", "3-629\3"])

**Comment by walterxie** [comment]
From Alexei:
Wouldn't you rather have: `L = nchar(codon);` and produce an Integer[]? And then reference L[0], L[1] and L[2] ?

**Comment by walterxie** [comment]
options = {ageDirection="forward", ageRegex="s(\d+)$"};
  taxa = readTaxa(file="examples/RSV2.nex", options= options)
  codon0 = nexus(file="examples/RSV2.nex", charset="3-629\3", taxa = taxa);
  codon1 = nexus(file="examples/RSV2.nex", charset="4-629\3", taxa = taxa);
  codon2 = nexus(file="examples/RSV2.nex", charset="5-629\3", taxa = taxa);

**Comment by walterxie** [comment]
```
  options = {ageDirection="forward", ageRegex="s(\d+)$"};
  file="examples/RSV2.nex";
  data = readNexus(file= file, options= options);
  codon0 = data. charset("3-629\3");
```

**Comment by walterxie** [comment]
Cannot use `data` as var, which is reserved.
data {
  options = {ageDirection="forward", ageRegex="s(\d+)$"};
  D = readNexus(file="examples/RSV2.nex", options=options);
  codon0 = D.charset("3-629\3");
  L0 = nchar(sites=codon0);
  taxa = D.taxa();
  codon1 = D.charset("4-629\3");
  L1 = nchar(sites=codon1);
  codon2 = D.charset("5-629\3");
  L2 = nchar(sites=codon2);
}
model {
  π ~ Dirichlet(conc=[2.0, 2.0, 2.0, 2.0]);
  Q = f81(freq=π);
  mu ~ LogNormal(meanlog=-4.5, sdlog=0.5);
  Θ ~ LogNormal(meanlog=3, sdlog=1);
  ψ ~ Coalescent(taxa=taxa, theta=Θ);
  codon0 ~ PhyloCTMC(L=L0, Q=Q, mu=mu, tree=ψ);
  codon1 ~ PhyloCTMC(L=L1, Q=Q, mu=mu, tree=ψ);
  codon2 ~ PhyloCTMC(L=L2, Q=Q, mu=mu, tree=ψ);
}

**Comment by walterxie** [comment]
data {
  options = {ageDirection="forward", ageRegex="s(\d+)$"};
  D = readNexus(file="examples/RSV2.nex", options=options);
  taxa = D.taxa();
  codon0 = D.charset("3-629\3");
  codon1 = D.charset("4-629\3");
  codon2 = D.charset("5-629\3");
}
model {
  π ~ Dirichlet(conc=[2.0, 2.0, 2.0, 2.0]);
  Q = f81(freq=π);
  mu ~ LogNormal(meanlog=-4.5, sdlog=0.5);
  Θ ~ LogNormal(meanlog=3, sdlog=1);
  ψ ~ Coalescent(taxa=taxa, theta=Θ);
  codon0 ~ PhyloCTMC(L=codon0.nchar(), Q=Q, mu=mu, tree=ψ);
  codon1 ~ PhyloCTMC(L=codon1.nchar(), Q=Q, mu=mu, tree=ψ);
  codon2 ~ PhyloCTMC(L=codon2.nchar(), Q=Q, mu=mu, tree=ψ);
}
