### ISSUE TITLE
CodeColorizer fails with exception for commands like sample(1000);

### ISSUE THREAD

**Issue by alexeid** [LinguaPhylo/linguaPhylo#57]
The CodeColorizer does not handle commands that are separate from the LPHY language. An exception is thrown due to a parsing error.

A correct implementation would recognise a command and treat it separately.

**Comment by walterxie** [comment]
Not sure if I understand the problem, but there is `sample` button to do so.

**Comment by walterxie** [comment]
`sample` is not in the commands anymore.
