### ISSUE TITLE
Re-run model block code if data block updated.

### ISSUE THREAD

**Issue by alexeid** [LinguaPhylo/linguaPhylo#66]
If a new line is executed in the data block then the whole model block needs to be re-executed.

(An even better idea would be to determine the lines in the model block that are dependent on the new data block line).

**Comment by walterxie** [comment]
I think this is solved by editing the value inside square button.

**Comment by walterxie** [comment]
But new issue #183

**Comment by walterxie** [comment]
The current issue in studio is that values are not changed, after changing any of parameter value through square box (constants). Triggering `sample` event after changing value may be experience for a complex model. So a temporary solution is to create a option to make "square" editable or not, but not editable as default.

**Comment by walterxie** [comment]
type new value for data block from studio console, the model will be re-sampled, for each input (press enter key to execute).
