### ISSUE TITLE
Improper dependency on AbstractAlignment in AlignmentComponent

### ISSUE THREAD

**Issue by alexeid** [LinguaPhylo/linguaPhylo#77]
The AlignmentComponent should be able to render *any* Alignment. Right now it is written so that it can only render Alignments that extend AbstractAlignment. It is bad design to have the entry point to a object hierarchy be an abstract class. Abstract classes are to help the developer organise the code within a package or subclass hierarchy. Code outside of the Java package or subclass hierarchy should generally not depend on abstract classes. The purpose of the Alignment interface is to define all shared behaviour of all alignments, regardless of implementation. The Alignment interface must be sufficient to render an alignment and also *absolutely* minimal. AlignmentComponent should not depend on AbstractAlignment, but only on Alignment interface.

There are other places that have the same problem of depending on AbstractAlignment rather than Alignment.

**Comment by walterxie** [comment]
related to #56
