### ISSUE TITLE
Nexus function should take either a String or a String[] for charset argument

### ISSUE THREAD

**Issue by alexeid** [LinguaPhylo/linguaPhylo#82]
Right now the nexus function takes a String that can be formatted as an array of Strings, or as a single charset. It should take an actual array of Strings (or a single String) so that the String array, so that no extra parsing is done by the Nexus function itself, and so that the array can be built by LPhy statements if necessary.

The following should be valid:

D = nexus(file="a.nex", charset=["1-100", "101-200", "201-300"])
D = nexus(file="a.nex", charset="1-100")

The following should be **invalid**:

D = nexus(file="a.nex", charset="[1-100, 101-200, 201-300]")

I think the code is already doing the right thing, but the following code declares the input parameter as type String when it might be a String[], it should instead declare the type as raw and give a comment that both String and String[] are accepted. There should be appropriate validation at construction and setParam.

https://github.com/LinguaPhylo/linguaPhylo/blob/33a3c4cbaa301bb722e003f750efc7b3d009f998/src/lphy/core/functions/Nexus.java#L39-L41

**Comment by walterxie** [comment]
add validation to setParam()
