### ISSUE TITLE
merge "part" in nexus function into "charset"

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#85]
Merge argument "part" in `nexus` into "charset".
Create a "partition name guesser": if the value is a name string (e.g. containing char, or _), then do as the argument "part" does, and if it only contains {numbers, -, \}, then do as previous "charset" does, otherwise throw exception.

**Comment by alexeid** [comment]
A regex for charset is "^([0-9]+)-([0-9]+)(/[0-9]+)*$"

**Comment by alexeid** [comment]
If it doesn't match this then check if the string matches a defined charset in the nexus file. If not then it is an error.
