### ISSUE TITLE
should TaxaCharacterMatrix extend HasTaxa or even Taxa?

### ISSUE THREAD

**Issue by walterxie** [LinguaPhylo/linguaPhylo#88]
@alexeid `HasTaxa` has `Taxa getTaxa();`  which is duplicated in `TaxaCharacterMatrix` 

https://github.com/LinguaPhylo/linguaPhylo/blob/df631f85a65b55494e284e631c6d7a4f76467a84/src/lphy/evolution/alignment/TaxaCharacterMatrix.java#L22-L25

It should make `TaxaCharacterMatrix<T> extends NChar,  HasTaxa`

**Comment by walterxie** [comment]
Furthermore, should `TaxaCharacterMatrix extends Taxa` instead? My understanding TaxaCharacterMatrix = Taxa + Matrix.

**Comment by alexeid** [comment]
Yes, should extend HasTaxa

**Comment by walterxie** [comment]
In addition, I am not sure whether I understand your design properly. It will be helpful to document the usage and scope of HasTaxa, Taxa, and maybe MultiDimensional (this seems unnecessary, since ntaxa() does the job, and I cannot think of how this could be shared with other data).

**Comment by walterxie** [comment]
@alexeid I think TaxaCharacterMatrix should also extend `MultiDimensional`, so I can start refactor `Taxa` to a Class later
